version: "3.8"
services: 
  frontend:
    container_name: frontend
    build:
      context: ../../web/
      target: dev
    restart: always
    command: npm run dev
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true # FOR WINDOWS
    volumes:
      - ../../web:/web
      - /web/node_modules
      - /web/.next
    ports:
      - 3000:3000
  backend:
    container_name: backend
    build:
      context: ../../api/
    volumes:
      - ../../api/app/:/app
    command: >
      uvicorn main:app --host 0.0.0.0 --port 3001 --reload
    ports:
      - 3001:3001