version: "3.8"
services: 
  frontend:
    container_name: frontend
    build:
      context: ../../web/
      target: dev
    restart: always
    # command: npm run dev-debug
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true # FOR WINDOWS
      # - NODE_OPTIONS='--inspect=0.0.0.0:9229'
    volumes:
      - ../../web:/web
      - /web/node_modules
      - /web/.next
    ports:
      - 3000:3000
      - 9229:9229 # Node.js debugger port
    # For debugging, ensure the inspect flag is passed
    # entrypoint: ["node", "--inspect=0.0.0.0:9229", "npm", "dev"]
    entrypoint: ["sh", "-c", "npm run dev-debug"]
  
  backend:
    container_name: backend
    build:
      context: ../../api/
    volumes:
      - ../../api/app/:/app
    ports:
      - 3001:3001
      - 5678:5678 # Python debug port
    environment:
      - PYTHONPATH=/app
    # https://github.com/microsoft/debugpy --wait-for-client if you want to wait until an debug connection is started.
    entrypoint: ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3001", "--reload", "--reload-dir", "/app"]